### ISSUE TITLE
luximono.sty with MacTeX

### ISSUE THREAD

**Issue by ksmandersen** [david-christiansen/itu-thesis#12]
I went down in a bit of rabbit hole trying to figure out how to install this font. Luxmono is not part of the default MacTeX distro and has to bo installed separately. Here is how for other people with the problem:

make sure that the texbin dir is in your path. Try to use ``texlua``. If the command is not found you need to adjust your ``$PATH``. On El Capitan you will need to add ``/Library/TeX/texbin`` to your path.

```bash
wget http://tug.org/fonts/getnonfreefonts/install-getnonfreefonts
chmod u+x install-getnonfreefonts
sudo ./install-getnonfreefonts
```

the sudo is important since it has to install fonts in your /Library folders. If it succeeds then run:

```bash
sudo getnonfreefonts-sys luximono
```

**Comment by david-christiansen** [comment]
Yes, this is how to do it. Would you mind sending a PR with this in the README? Otherwise I'll get to it in a week or two after some current traveling is done.

**Comment by david-christiansen** [comment]
BTW, this is also (modulo a few paths) what is necessary on Linux systems.

**Comment by ksmandersen** [comment]
Sure, I'll make a PR
